server.port: 9002
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

logging:
  level:
    root: INFO
    example: DEBUG
    xorg.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.config.activate.on-profile: docker

server.port: 8080

spring.data.mongodb.host: mongodb